### ISSUE TITLE
Test reform

### ISSUE THREAD

**Issue by rrbutani** [ut-utp/core#169]
### what

Tracking issue for `cargo t` showing all green.

The idea is that you should be able to clone this repo, run `nix develop` and then `cargo t` and have all the tests run and pass.

Specifically:
  - [ ] all the tests should pass
  - [ ] running the tests should require no extra setup
  - [ ] there should be no uncaptured `stdout`/`stderr` output from the tests
  - [ ] we should have no flaky tests
  - [ ] we should measure and report test coverage
  - [ ] `cargo t` should run in <10s
  - [ ] we should clean up test macros and APIs
     + i.e. having `single_test`, etc. support labels
  - [ ] we should make some kind of judgement about what adequate testing for each module is/what we want to add
     + prop tests, fuzzing, etc.
  - [ ] we should decide if we want to expose parts of the test suite to implementors/how to best do this
     + i.e. for the instruction interpreter, perhaps have all the tests reference a macro-defined `crate::init() -> impl InstructionInterpreter` (or something like that)

### steps

The first step is to get all the tests passing.

Doing this on a crate by crate basis, taking the opportunity to do some test related cleanup as we go:

  - [x] `application-support` (no tests, currently)
  - [ ] `baseline-sim` ()
  - [ ] `benches` ()
     + these are still run as part of `cargo t` but not actually measured
  - [ ] `device-support` ()
  - [ ] `isa` ()
  - [x] `macros` (no tests, currently)
  - [ ] `os` ()
  - [ ] `shims` ()
  - [ ] `test-infrastructure` ()
  - [ ] `traits` ()
